name: Deploy Airflow DAGs to MWAA

on:
  push:
    branches:
      - main   # or your deployment branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: eu-north-1   # change to your region

      - name: Sync DAGs
        run: |
          aws s3 sync Airflow/dags s3://aws-devtest-bucket/airflow/dags/ --delete

      - name: Sync CODE
        run: |
          aws s3 sync Airflow/code/ s3://aws-devtest-bucket/airflow/code/ --delete

      - name: Sync Plugins
        run: |
          aws s3 sync Airflow/plugins/ s3://aws-devtest-bucket/airflow/plugins/ --delete

      - name: Upload requirements.txt
        run: |
          if [ -f requirements.txt ]; then
            aws s3 cp Airflow/requirements/requirements.txt s3://aws-devtest-bucket/airflow/requirements.txt
          fi
